In [34]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split as tts
from sklearn.linear_model import LinearRegression as lrr
data=pd.read_csv("C:/Users/CS-06/OneDrive/place.csv")
print(data)

     cgpa  package
0    6.89     3.26
1    5.12     1.98
2    7.82     3.25
3    7.42     3.67
4    6.94     3.57
..    ...      ...
195  6.93     2.46
196  5.89     2.57
197  7.21     3.24
198  7.63     3.96
199  6.22     2.33

[200 rows x 2 columns]


In [13]:
print(data.isnull().sum())

cgpa       0
package    0
dtype: int64


In [15]:
x=data.iloc[:,[-2]].values
y=data.iloc[:,[-1]].values
print(x)
print(y)

[[6.89]
 [5.12]
 [7.82]
 [7.42]
 [6.94]
 [7.89]
 [6.73]
 [6.75]
 [6.09]
 [8.31]
 [5.32]
 [6.61]
 [8.94]
 [6.93]
 [7.73]
 [7.25]
 [6.84]
 [5.38]
 [6.94]
 [7.48]
 [7.28]
 [6.85]
 [6.14]
 [6.19]
 [6.53]
 [7.28]
 [8.31]
 [5.42]
 [5.94]
 [7.15]
 [7.36]
 [8.1 ]
 [6.96]
 [6.35]
 [7.34]
 [6.87]
 [5.99]
 [5.9 ]
 [8.62]
 [7.43]
 [9.38]
 [6.89]
 [5.95]
 [7.66]
 [5.09]
 [7.87]
 [6.07]
 [5.84]
 [8.63]
 [8.87]
 [9.58]
 [9.26]
 [8.37]
 [6.47]
 [6.86]
 [8.2 ]
 [5.84]
 [6.6 ]
 [6.92]
 [7.56]
 [5.61]
 [5.48]
 [6.34]
 [9.16]
 [7.36]
 [7.6 ]
 [5.11]
 [6.51]
 [7.56]
 [7.3 ]
 [5.79]
 [7.47]
 [7.78]
 [8.44]
 [6.85]
 [6.97]
 [6.94]
 [8.99]
 [6.59]
 [7.18]
 [7.63]
 [6.1 ]
 [5.58]
 [8.44]
 [4.26]
 [4.79]
 [7.61]
 [8.09]
 [4.73]
 [6.42]
 [7.11]
 [6.22]
 [7.9 ]
 [6.79]
 [5.83]
 [6.63]
 [7.11]
 [5.98]
 [7.69]
 [6.61]
 [7.95]
 [6.71]
 [5.13]
 [7.05]
 [7.62]
 [6.66]
 [6.13]
 [6.33]
 [7.76]
 [7.77]
 [8.18]
 [5.42]
 [8.58]
 [6.94]
 [5.84]
 [8.35]
 [9.04]
 [7.12]
 [7.4 ]
 [7.39]
 [5.23]
 [6.5 ]
 [5.12]
 [5.1 ]
 [6.06]


In [16]:
x_train,x_test,y_train,y_test=tts(x,y,test_size=0.2)
print(x_train,x_test,y_train,y_test)

[[7.21]
 [7.29]
 [6.71]
 [6.94]
 [7.36]
 [7.2 ]
 [9.04]
 [6.51]
 [6.94]
 [6.06]
 [6.31]
 [7.09]
 [5.91]
 [7.38]
 [5.84]
 [7.3 ]
 [6.14]
 [7.91]
 [7.66]
 [7.42]
 [7.84]
 [6.13]
 [8.15]
 [6.68]
 [5.13]
 [8.58]
 [7.3 ]
 [8.22]
 [6.89]
 [6.19]
 [6.92]
 [7.13]
 [5.98]
 [6.89]
 [5.48]
 [6.47]
 [4.57]
 [8.99]
 [5.88]
 [6.05]
 [7.04]
 [5.84]
 [6.22]
 [7.56]
 [7.15]
 [6.75]
 [5.1 ]
 [8.37]
 [6.86]
 [7.11]
 [6.34]
 [7.32]
 [6.79]
 [4.73]
 [5.79]
 [5.42]
 [7.28]
 [6.19]
 [7.69]
 [6.37]
 [7.19]
 [7.87]
 [7.48]
 [6.97]
 [8.93]
 [5.94]
 [6.93]
 [6.09]
 [6.76]
 [8.2 ]
 [8.1 ]
 [8.65]
 [5.61]
 [6.78]
 [6.94]
 [4.79]
 [7.57]
 [5.23]
 [8.87]
 [6.73]
 [8.6 ]
 [6.07]
 [7.56]
 [8.62]
 [9.16]
 [6.61]
 [7.39]
 [6.53]
 [8.44]
 [7.11]
 [7.95]
 [5.84]
 [8.71]
 [7.47]
 [7.77]
 [7.08]
 [5.11]
 [5.58]
 [7.28]
 [5.9 ]
 [8.44]
 [7.14]
 [8.13]
 [8.11]
 [5.84]
 [8.35]
 [7.88]
 [6.26]
 [6.19]
 [8.09]
 [9.06]
 [8.28]
 [9.26]
 [5.99]
 [7.14]
 [7.18]
 [6.93]
 [7.73]
 [6.33]
 [6.84]
 [8.18]
 [7.35]
 [9.38]
 [6.29]
 [5.95]


In [21]:
ls=lrr()
ls.fit(x_train,y_train)

LinearRegression()

In [5]:
y_predict=ls.predict(x_test)
print(y_predict)

[[2.97429502]
 [3.10218264]
 [3.01877767]
 [2.8297264 ]
 [3.89174971]
 [1.9456337 ]
 [3.48584551]
 [2.97985535]
 [3.01321734]
 [2.95761402]
 [3.68601745]
 [2.90757104]
 [3.49696618]
 [2.36821889]
 [3.49140584]
 [3.05769999]
 [1.76214276]
 [2.84084706]
 [1.79550475]
 [2.77412309]
 [2.60175281]
 [1.93451304]
 [3.10774297]
 [3.19114795]
 [3.63041413]
 [2.86864872]
 [4.030758  ]
 [2.34597756]
 [4.12528363]
 [3.4135612 ]
 [3.35795789]
 [3.30235457]
 [2.00679735]
 [2.54058917]
 [3.75274142]
 [3.1299843 ]
 [2.95205369]
 [2.66847679]
 [3.30791491]
 [2.64067513]]


In [17]:
train_accuracy=ls.score(x_train,y_train)
test_accuracy=ls.score(x_test,y_test)
print(train_accuracy)
print(test_accuracy)

0.7713198327342451
0.7802684037144905


In [18]:
from sklearn.metrics import mean_squared_error
msc=mean_squared_error(y_test,y_predict)
rmsc=np.sqrt(msc)
print("MSE:", msc)
print("RMSE:", rmsc)

MSE: 0.902657840293419
RMSE: 0.9500830702067157


In [19]:
y_test

array([[2.01],
       [1.94],
       [2.72],
       [2.2 ],
       [3.09],
       [2.89],
       [1.98],
       [3.  ],
       [2.99],
       [2.88],
       [3.67],
       [3.51],
       [2.87],
       [3.25],
       [2.26],
       [4.  ],
       [3.02],
       [2.99],
       [3.04],
       [2.42],
       [2.93],
       [2.82],
       [1.86],
       [2.6 ],
       [2.21],
       [2.79],
       [2.18],
       [4.08],
       [2.76],
       [3.44],
       [3.54],
       [3.42],
       [3.23],
       [4.43],
       [2.61],
       [2.73],
       [2.42],
       [3.15],
       [1.86],
       [2.57]])

In [20]:
y_predict

array([[2.97429502],
       [3.10218264],
       [3.01877767],
       [2.8297264 ],
       [3.89174971],
       [1.9456337 ],
       [3.48584551],
       [2.97985535],
       [3.01321734],
       [2.95761402],
       [3.68601745],
       [2.90757104],
       [3.49696618],
       [2.36821889],
       [3.49140584],
       [3.05769999],
       [1.76214276],
       [2.84084706],
       [1.79550475],
       [2.77412309],
       [2.60175281],
       [1.93451304],
       [3.10774297],
       [3.19114795],
       [3.63041413],
       [2.86864872],
       [4.030758  ],
       [2.34597756],
       [4.12528363],
       [3.4135612 ],
       [3.35795789],
       [3.30235457],
       [2.00679735],
       [2.54058917],
       [3.75274142],
       [3.1299843 ],
       [2.95205369],
       [2.66847679],
       [3.30791491],
       [2.64067513]])

In [32]:

cgpa = float(input("Enter CGPA: "))

package = ls.predict([[cgpa]])

print("CGPA:", cgpa)
print("Predicted Package:", package[0][0], "LPA")

Enter CGPA: 9.2
CGPA: 9.2
Predicted Package: 4.270453820468397 LPA
